spring.application.name=Warehouse_Inventory_System
# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_system

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=12345

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true